### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by s4sutler100** [ThePoultryMan/Lanterns-Belong-On-Walls#5]
**Game crash when enabled with other mods*
I turn on Lanterns-Belong-On-Walls in mod profile load launcher and press play 
game crashes.

I turn it off game works fine.  

[17:09:06] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.14.4
[17:09:07] [main/WARN]: Warnings were found!
 - Mod 'Reese's Sodium Options' (reeses-sodium-options) 1.4.0 recommends version 0.3.7 or later of sodium-extra, which is missing!
	 - You should install version 0.3.7 or later of sodium-extra for the optimal experience.
[17:09:07] [main/INFO]: Loading 71 mods:
	- antitoolbreak 1.0.0
	- autofish 0.9.4
	- autoswitch 3.5.2
	- autoswitch-api 1.0.0 via autoswitch
	- cateyes 2.0.1
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57
	- clumps 8.0.0+5
	- fabric 0.46.6+1.18
	- fabric-api-base 0.4.2+d7c144a865 via fabric
	- fabric-api-lookup-api-v1 1.5.3+d7c144a865 via fabric
	- fabric-biome-api-v1 6.0.2+d7c144a865 via fabric
	- fabric-blockrenderlayer-v1 1.1.10+3ac43d9565 via fabric
	- fabric-command-api-v1 1.1.7+d7c144a865 via fabric
	- fabric-commands-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.19+d7c144a865 via fabric
	- fabric-content-registries-v0 0.4.9+d7c144a865 via fabric
	- fabric-crash-report-info-v1 0.1.9+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.10+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.6+d7c144a865 via fabric
	- fabric-events-interaction-v0 0.4.17+d7c144a865 via fabric
	- fabric-events-lifecycle-v0 0.2.9+d7c144a865 via fabric
	- fabric-game-rule-api-v1 1.0.11+d7c144a865 via fabric
	- fabric-item-api-v1 1.3.1+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.7+3ac43d9565 via fabric
	- fabric-key-binding-api-v1 1.0.9+d7c144a865 via fabric
	- fabric-keybindings-v0 0.2.7+b4f4f6cd65 via fabric
	- fabric-lifecycle-events-v1 1.4.13+713c266865 via fabric
	- fabric-loot-tables-v1 1.0.9+d7c144a865 via fabric
	- fabric-mining-level-api-v1 1.0.7+d7c144a865 via fabric
	- fabric-mining-levels-v0 0.1.12+b4f4f6cd65 via fabric
	- fabric-models-v0 0.3.4+d7c144a865 via fabric
	- fabric-networking-api-v1 1.0.19+d7c144a865 via fabric
	- fabric-networking-v0 0.3.6+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.5+737332ce65 via fabric
	- fabric-object-builders-v0 0.7.13+d7c144a865 via fabric
	- fabric-particles-v1 0.2.10+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.2+ad01bfbd65 via fabric
	- fabric-renderer-api-v1 0.4.11+b0b66fc365 via fabric
	- fabric-renderer-indigo 0.4.15+6825030165 via fabric
	- fabric-renderer-registries-v1 3.2.10+b4f4f6cd65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.5+d7c144a865 via fabric
	- fabric-rendering-fluids-v1 0.1.19+3ac43d9565 via fabric
	- fabric-rendering-v0 1.1.12+b4f4f6cd65 via fabric
	- fabric-rendering-v1 1.10.6+713c266865 via fabric
	- fabric-resource-conditions-api-v1 1.0.2+d7c144a865 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via walllanterns
	- fabric-screen-api-v1 1.0.8+d7c144a865 via fabric
	- fabric-screen-handler-api-v1 1.1.12+d7c144a865 via fabric
	- fabric-structure-api-v1 2.1.3+d7c144a865 via fabric
	- fabric-tag-extensions-v0 1.2.9+d7c144a865 via fabric
	- fabric-textures-v0 1.0.10+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.9+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.10+c329913d65 via fabric
	- fabricloader 0.14.4
	- java 17
	- journeymap-api-fabric 1.18.1-1.8-fabric-SNAPSHOT via journeymap-fabric
	- journeymap-fabric 5.8.1
	- litematica 0.10.4
	- litematicatool 1.3.2
	- malilib 0.11.8
	- minecraft 1.18.1
	- modmenu 3.0.1
	- org_aeonbits_owner_owner 1.0.12 via autoswitch
	- org_joml_joml 1.10.2 via sodium
	- reeses-sodium-options 1.4.0
	- signtools 1.0.0
	- sodium 0.4.0-alpha6+build.14
	- walllanterns 1.2.0
	- xaerominimap 22.3.0
	- xaeroworldmap 1.20.3.1
[17:09:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Steven%20Sutler/curseforge/minecraft/Install/libraries/net/fabricmc/sponge-mixin/0.11.3+mixin.0.8.5/sponge-mixin-0.11.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:09:12] [main/INFO]: Compatibility level set to JAVA_17
[17:09:12] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 0 override(s) found
[17:09:12] [main/WARN]: Error loading class: net/minecraft/class_6861 (java.lang.ClassNotFoundException: net/minecraft/class_6861)
[17:09:12] [main/WARN]: @Mixin target net.minecraft.class_6861 was not found fabric-resource-loader-v0.mixins.json:LifecycledResourceManagerImplMixin from mod fabric-resource-loader-v0
[17:09:13] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[17:09:14] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[17:09:14] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[17:09:23] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin from mod fabric-lifecycle-events-v1::handler$zdp000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[17:09:30] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:09:31] [Render thread/INFO]: Setting user: S4Sutler100
[17:09:32] [Render thread/INFO]: Initializing ServerSide Packet Registries
[17:09:32] [Render thread/INFO]: [STDOUT]: Hello Fabric world!
[17:09:33] [Render thread/INFO]: AutoSwitch Loaded
[17:09:33] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[17:09:34] [Render thread/INFO]: Loading Xaero's Minimap - Stage 1/2
[17:09:36] [Render thread/INFO]: Loading Xaero's World Map - Stage 1/2
[17:09:36] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[17:09:42] [Render thread/INFO]: Narrator library for x64 successfully loaded
[17:09:43] [Render thread/INFO]: Reloading ResourceManager: Fabric Mods (Anti Tool Break, Autofish, AutoSwitch, AutoSwitch API, Cat Eyes, Cloth Config v6, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Journeymap, Litematica, Litematia Tool, MaLiLib, Mod Menu, Reese's Sodium Options, Sign Tools, Sodium, Lanterns Belong on Walls, Xaero's Minimap, Xaero's World Map), Default, Programmer Art (Anti Tool Break, Autofish, AutoSwitch, AutoSwitch API, Cat Eyes, Cloth Config v6, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Conditions API (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Journeymap, Litematica, Litematia Tool, MaLiLib, Mod Menu, Reese's Sodium Options, Sign Tools, Sodium, Lanterns Belong on Walls, Xaero's Minimap, Xaero's World Map), NightVision_1.13+.zip, Broken_Tools_V2_1.18.zip, Disable+menu+music.zip
[17:09:43] [Render thread/ERROR]: Mixin apply for mod fabric-resource-loader-v0 failed fabric-resource-loader-v0.mixins.json:SimpleResourceReloadMixin from mod fabric-resource-loader-v0 -> net.minecraft.class_4014: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on method_40087 could not find any targets matching 'Lnet/minecraft/class_4014;method_40087(Lnet/minecraft/class_3300;Ljava/util/List;Ljava/util/concurrent/Executor;Ljava/util/concurrent/Executor;Ljava/util/concurrent/CompletableFuture;Z)Lnet/minecraft/class_4011;' in net.minecraft.class_4014. Using refmap fabric-resource-loader-v0-refmap.json [PREINJECT Applicator Phase -> fabric-resource-loader-v0.mixins.json:SimpleResourceReloadMixin from mod fabric-resource-loader-v0 -> Prepare Injections ->  -> handler$zhf000$method_40087(Lnet/minecraft/class_3300;Ljava/util/List;Ljava/util/concurrent/Executor;Ljava/util/concurrent/Executor;Ljava/util/concurrent/CompletableFuture;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on method_40087 could not find any targets matching 'Lnet/minecraft/class_4014;method_40087(Lnet/minecraft/class_3300;Ljava/util/List;Ljava/util/concurrent/Executor;Ljava/util/concurrent/Executor;Ljava/util/concurrent/CompletableFuture;Z)Lnet/minecraft/class_4011;' in net.minecraft.class_4014. Using refmap fabric-resource-loader-v0-refmap.json [PREINJECT Applicator Phase -> fabric-resource-loader-v0.mixins.json:SimpleResourceReloadMixin from mod fabric-resource-loader-v0 -> Prepare Injections ->  -> handler$zhf000$method_40087(Lnet/minecraft/class_3300;Ljava/util/List;Ljava/util/concurrent/Executor;Ljava/util/concurrent/Executor;Ljava/util/concurrent/CompletableFuture;ZLorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor59.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1330) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1043) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:409) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:318) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) [fabric-loader-0.14.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.class_3304.method_18232(class_3304.java:137) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:623) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:199) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.4.jar:?]
[17:09:43] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[17:09:44] [Render thread/INFO]: Failed to find module info for C:\Users\Steven Sutler\curseforge\minecraft\Install\bin\326a-4f49-1c92-82ba\lwjgl.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.4.jar:?]
[17:09:44] [Render thread/INFO]: Failed to find module info for C:\Users\Steven Sutler\curseforge\minecraft\Install\bin\326a-4f49-1c92-82ba\glfw.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.4.jar:?]
[17:09:45] [Render thread/INFO]: Failed to find module info for C:\Users\Steven Sutler\curseforge\minecraft\Install\bin\326a-4f49-1c92-82ba\lwjgl_opengl.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.4.jar:?]
[17:09:45] [Render thread/INFO]: Failed to find module info for C:\Users\Steven Sutler\curseforge\minecraft\Install\bin\326a-4f49-1c92-82ba\lwjgl_stb.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.4.jar:?]
[17:09:45] [Render thread/INFO]: Failed to find module info for C:\Users\Steven Sutler\curseforge\minecraft\Install\bin\326a-4f49-1c92-82ba\OpenAL.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.4.jar:?]
[17:09:45] [Render thread/INFO]: Failed to find module info for C:\Users\Steven Sutler\curseforge\minecraft\Install\bin\326a-4f49-1c92-82ba\SAPIWrapper_x64.dll
com.sun.jna.platform.win32.Win32Exception: The specified resource type cannot be found in the image file.
	at net.minecraft.class_6498.method_37964(class_6498.java:62) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37961(class_6498.java:48) ~[client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37968(class_6498.java:132) ~[client-intermediary.jar:?]
	at net.minecraft.class_129.method_577(class_129.java:84) [client-intermediary.jar:?]
	at net.minecraft.class_6498.method_37966(class_6498.java:131) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:207) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.4.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.4.jar:?]

**Comment by ThePoultryMan** [comment]
His doesn't look like an issue with my mod. Try installing https://modrinth.com/mod/sodium-extra/versions to see if it fixes the issue. That seems to be the issue based on the logs.

**Comment by JoelZBub** [comment]
Here is a crash report with same issue. Pack loads fine without LanternsBoW, crashes when it's removed. 
Report points to mixins conflict with Fabrication.
[https://gist.github.com/JoelZBub/b57e51494b79155d136569b1dd01e6cd](url)

**Comment by JoelZBub** [comment]
It might help if the original poster added a crash report instead of just a copy/paste of the latest.log

**Comment by s4sutler100** [comment]
> This doesn't look like an issue with my mod. Try installing https://modrinth.com/mod/sodium-extra/versions to see if it fixes the issue. That seems to be the issue based on the logs.

ty
